using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Datacute.IncrementalGeneratorExtensions.GeneratorTests
{
    public class GeneratorTests
    {
        [Fact]
        public void RunGenerators_EmitsOneHintFilePerEmbeddedCsResource()
        {
            // Arrange
            var compilation = CreateEmptyCompilation();
            var driver = CSharpGeneratorDriver.Create(new Generator().AsSourceGenerator());

            var generatorAssembly = typeof(Generator).Assembly;
            var expectedHintNames = generatorAssembly
                .GetManifestResourceNames()
                .Where(n => n.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                .Select(n => Path.GetFileNameWithoutExtension(Path.GetFileName(n)) + ".g.cs")
                .OrderBy(s => s)
                .ToArray();

            // Act
            var resultDriver = driver.RunGenerators(compilation);
            var result = resultDriver.GetRunResult();

            // Assert
            Assert.Empty(result.Diagnostics);

            var generatedHintNames = result.GeneratedTrees
                .Select(t => GetHintName(t.FilePath))
                .OrderBy(s => s)
                .ToArray();
            Assert.Equal(expectedHintNames, generatedHintNames);
            Assert.NotEmpty(generatedHintNames);
        }

        [Fact]
        public void RunGenerators_EmittedFile_StartsWithAutoGeneratedHeader()
        {
            // Arrange
            var compilation = CreateEmptyCompilation();
            var driver = CSharpGeneratorDriver.Create(new Generator().AsSourceGenerator());

            // Act
            var resultDriver = driver.RunGenerators(compilation);
            var result = resultDriver.GetRunResult();
            var firstTree = result.GeneratedTrees.First();
            var text = firstTree.GetText().ToString();

            // Assert — the header is what consumers see and what enables IDE
            // suppression of generated code; its shape is part of the contract.
            Assert.StartsWith("//---", text);
            Assert.Contains("<auto-generated>", text);
            Assert.Contains("</auto-generated>", text);
            Assert.Contains("Datacute.IncrementalGeneratorExtensions", text);
        }

        private static CSharpCompilation CreateEmptyCompilation()
            => CSharpCompilation.Create(
                "Test",
                new[] { CSharpSyntaxTree.ParseText(string.Empty) },
                new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });

        private static string GetHintName(string filePath)
            => filePath.Replace('\\', '/').Split('/').Last();
    }
}
