// <auto-generated>
// This file is part of the Datacute.IncrementalGeneratorExtensions package.
// It is included as a source file and should not be modified.
// </auto-generated>

#if !DATACUTE_EXCLUDE_GENERATORSTAGE
namespace Datacute.IncrementalGeneratorExtensions
{
    /// <summary>
    /// Represents the various stages and method calls of an incremental generator.
    /// </summary>
    /// <remarks>
    /// This enum can be used with the LightweightTrace methods.
    /// Each value corresponds to a specific stage or method in the generator's lifecycle.
    /// </remarks>
    public enum GeneratorStage
    {
        Initialize = 0,
        Cancellation = 1,

        // Output registration stages
        RegisterPostInitializationOutput = 2,
        RegisterSourceOutput = 3,
        RegisterImplementationSourceOutput = 4,

        // PostInitializationContext Methods
        PostInitializationContextAddEmbeddedAttributeDefinition = 5,
        PostInitializationContextAddSource = 6,

        // SourceProductionContext Methods
        SourceProductionContextAddSource = 7,
        SourceProductionContextReportDiagnostic = 8,
        
        // SyntaxProvider Methods
        CreateSyntaxProvider = 9,
        ForAttributeWithMetadataName = 10,
        ForAttributeWithMetadataNamePredicate = 11,
        ForAttributeWithMetadataNameTransform = 12,

        // Methods on various IncrementalValue(s) Providers
        CompilationProviderSelect = 13,
        ParseOptionsProviderSelect = 14,
        AdditionalTextsProviderSelect = 15,
        AnalyzerConfigOptionsProviderSelect = 16,
        MetadataReferencesProviderSelect = 17,
        
#if !DATACUTE_EXCLUDE_EQUATABLEIMMUTABLEARRAY
        // EquatableImmutableArray Counters
        EquatableImmutableArrayCacheHit = 18,
        EquatableImmutableArrayCacheMiss = 19,
        EquatableImmutableArrayCacheWeakReferenceRemoved = 20,
        EquatableImmutableArrayLength = 21,
#endif
    }
}
#endif