// <auto-generated>
// This file is part of the Datacute.IncrementalGeneratorExtensions package.
// It is included as a source file and should not be modified.
// </auto-generated>

#if !DATACUTE_EXCLUDE_GENERATORSTAGE
namespace Datacute.IncrementalGeneratorExtensions
{
    /// <summary>
    /// Represents the various stages and method calls of an incremental generator.
    /// </summary>
    /// <remarks>
    /// This enum can be used with the LightweightTrace methods.
    /// Each value corresponds to a specific stage or method in the generator's lifecycle.
    /// </remarks>
    public enum GeneratorStage
    {
        Initialize = 0,

        // Output registration stages
        RegisterPostInitializationOutput = 1,
        RegisterSourceOutput = 2,
        RegisterImplementationSourceOutput = 3,

        // PostInitializationContext Methods
        PostInitializationContextAddEmbeddedAttributeDefinition = 11,
        PostInitializationContextAddSource = 12,

        // SourceProductionContext Methods
        SourceProductionContextAddSource = 21,
        SourceProductionContextReportDiagnostic = 22,
        
        // SyntaxProvider Methods
        CreateSyntaxProvider = 41,
        ForAttributeWithMetadataNamePredicate = 42,
        ForAttributeWithMetadataNameTransform = 43,
        ForAttributeWithMetadataName = 44,

        // Methods on various IncrementalValue(s) Providers
        CompilationProviderSelect = 51,
        ParseOptionsProviderSelect = 61,
        AdditionalTextsProviderSelect = 71,
        AnalyzerConfigOptionsProviderSelect = 81,
        MetadataReferencesProviderSelect = 91
    }
}
#endif