using System;
using System.Collections.Immutable;
using System.Threading;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Datacute.IncrementalGeneratorExtensions.Tests
{
    public class SourceTextGeneratorBaseTests
    {
        private static readonly string NL = Environment.NewLine;

        // Test subclass: skip the dynamic auto-generated header (assembly name + version)
        // so output is deterministic, and emit a known body marker.
        private sealed class TestGenerator : SourceTextGeneratorBase<int>
        {
            public TestGenerator(in AttributeContextAndData<int> data)
                : base(data, CancellationToken.None) { }

            protected override void AppendAutoGeneratedComment() { /* skip dynamic header */ }

            protected override void AppendCustomMembers()
            {
                Buffer.AppendLine("// body");
            }
        }

        [Fact]
        public void AppendSource_GlobalNamespace_EmitsTypeWithoutNamespaceBlock()
        {
            // Arrange
            var data = MakeData(MakeTypeContext("", "Foo"), fileScoped: false, nullable: false);
            var gen = new TestGenerator(data);

            // Act
            var output = gen.GetSourceText().ToString();

            // Assert
            var expected = "public partial class Foo" + NL + "{" + NL + "    // body" + NL + "}" + NL;
            Assert.Equal(expected, output);
        }

        [Fact]
        public void AppendSource_FileScopedNamespace_EmitsSemicolonForm()
        {
            // Arrange
            var data = MakeData(MakeTypeContext("My.Ns", "Foo"), fileScoped: true, nullable: false);
            var gen = new TestGenerator(data);

            // Act
            var output = gen.GetSourceText().ToString();

            // Assert
            var expected =
                "namespace My.Ns;" + NL + NL +
                "public partial class Foo" + NL +
                "{" + NL +
                "    // body" + NL +
                "}" + NL;
            Assert.Equal(expected, output);
        }

        [Fact]
        public void AppendSource_ContainingType_OpensAndClosesMatchingBraces()
        {
            // Arrange — Outer wraps Inner; the test verifies that
            // AppendContainingTypesEndBlock emits exactly one closing brace per opening.
            var inner = MakeTypeContext("My.Ns", "Inner");
            var outer = MakeTypeContext("My.Ns", "Outer");
            var containing = ImmutableArray.Create(outer).ToEquatableImmutableArray();

            var data = new AttributeContextAndData<int>(inner, containing,
                attributeData: 0,
                isInFileScopedNamespace: true,
                isNullableContextEnabled: false);
            var gen = new TestGenerator(data);

            // Act
            var output = gen.GetSourceText().ToString();

            // Assert
            var expected =
                "namespace My.Ns;" + NL + NL +
                "public partial class Outer" + NL +
                "{" + NL +
                "    public partial class Inner" + NL +
                "    {" + NL +
                "        // body" + NL +
                "    }" + NL +
                "}" + NL;
            Assert.Equal(expected, output);
        }

        [Fact]
        public void AppendSource_NullableContextEnabled_EmitsPragmaBeforeNamespace()
        {
            // Arrange
            var data = MakeData(MakeTypeContext("", "Foo"), fileScoped: false, nullable: true);
            var gen = new TestGenerator(data);

            // Act
            var output = gen.GetSourceText().ToString();

            // Assert
            var expected =
                "#nullable enable" + NL + NL +
                "public partial class Foo" + NL +
                "{" + NL +
                "    // body" + NL +
                "}" + NL;
            Assert.Equal(expected, output);
        }

        private static TypeContext MakeTypeContext(string @namespace, string name)
            => new TypeContext(@namespace, name,
                isStatic: false, isPartial: true, isAbstract: false, isSealed: false,
                Accessibility.Public, "class", EquatableImmutableArray<string>.Empty);

        private static AttributeContextAndData<int> MakeData(TypeContext ctx, bool fileScoped, bool nullable)
            => new AttributeContextAndData<int>(ctx,
                EquatableImmutableArray<TypeContext>.Empty,
                attributeData: 0,
                isInFileScopedNamespace: fileScoped,
                isNullableContextEnabled: nullable);
    }
}
